### ISSUE TITLE
你好，尝试了你的模型压缩中的知识蒸馏，的确知识蒸馏能提高学生网络的精度，但是训练保存的model文件还是很大呀，而且教师网络越大，最后蒸馏模型训练后得到的权重文件也越大。

### ISSUE THREAD

**Issue by Crowpeng** [chengshengchan/model_compression#6]
我尝试查看了得到的学生模型权重文件，发现模型文件里依然保存有教师网络的权重。请问这算是模型压缩嘛？

**Comment by chengshengchan** [comment]
The weights of teacher model will be preserved during training procedure.
In testing time, the student network can be used independently.
